baseURL = 'https://example.org/'
languageCode = 'en-us'
defaultContentLanguage = "en"
title = 'Wonderland treadmill'
theme = 'hugo-vitae'
enableRobotsTXT = true

copyright = "© Copyright notice | [Vitae](https://github.com/dataCobra/hugo-vitae) theme for [Hugo](https://gohugo.io)"

[pagination]
# Enable pagination
enabled = true
# Number of pages to show in the pager
pagerSize = 5
# Number of posts to show per page
perPage = 5
# Show the pager on the homepage
homepage = true

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
# Enable dark mode as default
#darkmode = true

# Use homepage.md instead of a list of posts
homepage = false

# Add meta keywords in head part (Site Keywords or Tags of Page)
keywords = ["hugo", "vitae", "theme", "static"]

# Add meta description in head part
description = "A financial blog for the flimsical-minded."

# Add pagetitle to homepage <title> tag
pagetitle = "All about static site generation"

# Add a subtitle to your website
subtitle = "A financial blog for the flimsical-minded."

# Add math typesetting with KaTeX (Global with this Param)
math = false

# Optional 80x80 avatar image.
avatar = "img/lysanderg.png"

# Optional favicons for website
#favicon = true

# Add list of sections that should show up on the homepage
mainSections = ["posts"]

# Add list of Sections/Types that should no be considered by RSS
nofeedSections = [""]

# Deactivate Taxonomies for specific page types
#disableTaxoTypes = [""]

# Custom CSS applied to default styles. (Path could be "static/css/")
#customcss = "css/custom.css"

# Show reading time on a post
readingTime = false

# Show word count on a post
wordCount = false

# Show author on a post (groups with readingTime and wordCount)
hideAuthor = true

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 5

# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/dataCobra/hugo-vitae"

[[params.social]]
name = "Email"
icon = "fas fa-envelope"
cmd = "mailto:example@example.com"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "index.xml"
